use nvim_oxi as nvim;

use nvim::api::opts::{OptionOpts, OptionScope};
use nvim::api::set_option_value;

///
///
///
pub fn setup() {
    let opts = OptionOpts::builder().scope(OptionScope::Local).build();

    //
    // Enable hybrid number (Absolute and relative number)
    //
    let _ = set_option_value("number", true, &opts);
    let _ = set_option_value("relativenumber", true, &opts);
    let _ = set_option_value("signcolumn", "yes", &opts);

    // Hide the vim mode
    let _ = set_option_value("showmode", false, &opts);

    // No swapfile
    let _ = set_option_value("swapfile", false, &opts);

    // Share system clipboard
    let _ = set_option_value("clipboard", "unnamedplus", &opts);

    // Case-insensitive searching
    let _ = set_option_value("ignorecase", true, &opts);
    let _ = set_option_value("smartcase", true, &opts);

    // Show or disable a vertical bar to indicate the column limit position.
    let _ = set_option_value("colorcolumn", "80", &opts);

    //
    // Tab related
    //
    const TAB_INDENT_WIDTH: usize = 4;
    let _ = set_option_value("expandtab", true, &opts);
    let _ = set_option_value("smartindent", true, &opts);
    let _ = set_option_value("shiftround", true, &opts);
    let _ = set_option_value("shiftwidth", TAB_INDENT_WIDTH, &opts);
    let _ = set_option_value("tabstop", TAB_INDENT_WIDTH, &opts);
    let _ = set_option_value("softtabstop", TAB_INDENT_WIDTH, &opts);

    //
    // Send more characters for redraws, should make scrolling faster
    //
    let _ = set_option_value("ttyfast", true, &opts);
    let _ = set_option_value("lazyredraw", true, &opts);

    //
    // Open vertical split on the right side (your cursor will there)
    //
    let _ = set_option_value("splitright", true, &opts);
    let _ = set_option_value("splitbelow", true, &opts);

    //
    // Enable; spell; checking
    //
    // `]s` - go to next misspelled word
    // `[s` - go to prev misspelled word
    // `z=` - show the correct candidate list
    //
    let _ = set_option_value("spelllang", "en_us", &opts);

    // Completion options (for deoplete)
    let _ = set_option_value("completeopt", "menuone,noinsert,noselect", &opts);

    // Scroll off
    let _ = set_option_value("scrolloff", 10, &opts);

    //
    // Enable persistent undo
    //
    let _ = set_option_value("undofile", true, &opts);
    let _ = set_option_value("undodir", "~/.config/nvim/undo", &opts);

    //
    // True color support
    //
    // Enables 24-bit RGB color in the |TUI|.  Uses "gui" |:highlight|
    // attributes instead of "cterm" attributes. |guifg|
    // Requires an ISO-8613-3 compatible terminal.
    //
    // If you want to use default terminal color generated by `pywal-16-colors`,
    // then you CANNOT turn this on!!!
    //
    let _ = set_option_value("termguicolors", true, &opts);

    // Enable; cursor line
    let _ = set_option_value("cursorline", true, &opts);

    // `CursorLine` highlight group affect cursor position's line number and text
    let _ = set_option_value("cursorlineopt", "both", &opts);

    //
    // 1. `n-v-c:block-Cursor/lCursor`
    //
    //     In [Normal, Visual, Command] mode, use `block ` shape cusor and `Cursor1`
    //     or `lCursor1` highlight group instead of the default `inverse/reverse`
    //     highlight group.
    //
    // 2. `i-ci-ve:ver25-Cursor2/lCursor2`
    //
    //     In [Insert, Command line Insert, Virual with selection ] mode, use vertical
    //     bar shape cusor (bar width is 25% of the character width ),
    //
    //
    let _ = set_option_value(
        "guicursor",
        "n-v-c:block-Cursor1/lCursor1,i-ci-ve:ver25-Cursor2/lCursor2,r-cr:hor20,o:hor50",
        &opts,
    );

    //
    // Defines the default border style of floating windows. The default value
    // is empty, which is equivalent to "none". Valid values include:
    // - "bold": Bold line box.
    // - "double": Double-line box.
    // - "none": No border.
    // - "rounded": Like "single", but with rounded corners ("╭" etc.).
    // - "shadow": Drop shadow effect, by blending with the background.
    // - "single": Single-line box.
    // - "solid": Adds padding by a single whitespace cell.
    //
    let _ = set_option_value("winborder", "rounded", &opts);

    //
    // `:grep` command related
    //
    let _ = set_option_value("grepprg", "rg --no-heading --vimgrep", &opts);
    let _ = set_option_value("grepformat", "%f:%l:%c:%m", &opts);
}
